/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as LeakageRouteImport } from './routes/leakage'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'
import { Route as InvestigationCaseIdRouteImport } from './routes/investigation.$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const LeakageRoute = LeakageRouteImport.update({
  id: '/leakage',
  path: '/leakage',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationCaseIdRoute = InvestigationCaseIdRouteImport.update({
  id: '/investigation/$caseId',
  path: '/investigation/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/leakage': typeof LeakageRoute
  '/recovery': typeof RecoveryRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/investigation/$caseId': typeof InvestigationCaseIdRoute
  '/customers/': typeof CustomersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/leakage': typeof LeakageRoute
  '/recovery': typeof RecoveryRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/investigation/$caseId': typeof InvestigationCaseIdRoute
  '/customers': typeof CustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/leakage': typeof LeakageRoute
  '/recovery': typeof RecoveryRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/investigation/$caseId': typeof InvestigationCaseIdRoute
  '/customers/': typeof CustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/leakage'
    | '/recovery'
    | '/customers/$customerId'
    | '/investigation/$caseId'
    | '/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/leakage'
    | '/recovery'
    | '/customers/$customerId'
    | '/investigation/$caseId'
    | '/customers'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/leakage'
    | '/recovery'
    | '/customers/$customerId'
    | '/investigation/$caseId'
    | '/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  LeakageRoute: typeof LeakageRoute
  RecoveryRoute: typeof RecoveryRoute
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
  InvestigationCaseIdRoute: typeof InvestigationCaseIdRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leakage': {
      id: '/leakage'
      path: '/leakage'
      fullPath: '/leakage'
      preLoaderRoute: typeof LeakageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigation/$caseId': {
      id: '/investigation/$caseId'
      path: '/investigation/$caseId'
      fullPath: '/investigation/$caseId'
      preLoaderRoute: typeof InvestigationCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  LeakageRoute: LeakageRoute,
  RecoveryRoute: RecoveryRoute,
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
  InvestigationCaseIdRoute: InvestigationCaseIdRoute,
  CustomersIndexRoute: CustomersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
